Add license and copyright notice to every .py file
fatiando/harmonica pull request #201
Opened 2020-10-29 13:20 UTC by santisoler

Related to fatiando/maintenance#10

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

2020-10-29 13:30 UTC, leouieda requested changes

2020-10-29 13:30 UTC, leouieda commented on harmonica/datasets/__init__.py
> +# SPDX-License-Identifier: BSD-3-Clause
Ran the script twice?

2020-10-29 14:59 UTC, santisoler commented on harmonica/datasets/__init__.py
> +# SPDX-License-Identifier: BSD-3-Clause
:facepalm:

2020-11-09 13:51 UTC, leouieda approved these changes

2020-11-09 14:07 UTC, merged